### ISSUE TITLE
old.reddit.com URLs not supported

### ISSUE THREAD

**Issue by Mattwmaster58** [timorthi/redditraffler#123]
Basically the title.

**Comment by timorthi** [comment]
@Mattwmaster58 Thanks, I'll look into this!

**Comment by timorthi** [comment]
@Mattwmaster58 Could you clarify what you mean by "not supported"? I couldn't reproduce any error; I created a raffle just fine using an `old.reddit.com` URL.

**Comment by Mattwmaster58** [comment]
Wow, I really wish I documented this better at the time. I thought there was some sort of message like 'Invalid URL' and then it worked when I removed `old.` from the URL. I just tried it again myself and it worked fine, so not exactly sure what was going on there.

**Comment by timorthi** [comment]
No worries! Sounds like you might've actually encountered a flaky issue with the frontend URL validation, but I'm working on a UI rewrite so I'm ignoring non-urgent UI bugs going forward. I'd expect it to be fixed with the new UI release... whenever that may be! 😅
