### ISSUE TITLE
(Suggestion) API 

### ISSUE THREAD

**Issue by ghost** [timorthi/redditraffler#76]
Hey! Would be great if redditraffler had an API to fetch results from raffles and create new ones. Would enable giveaway subreddits to have dedicated bots to verify raffles, let OPs run a simple command eg: `/u/raffleB0t [criterias]`, blabla.

**Comment by timorthi** [comment]
Hi there, this is a good idea, though I have some plans for upgrades to the site that I think are of higher priority -- I'll definitely keep this in the back of my mind though!
